### ISSUE TITLE
missing preprocessing step

### ISSUE THREAD

**Issue by jsmithdlc** [SebastianHafner/SiameseSSL#1]
Hi,

thanks for sharing your work .There is a missing step in the preprocessing.py script, for generating the mask rasters (labels_rasters). I think this can be solved by integrating create_building_masks into the preprocessing code.

**Comment by SebastianHafner** [comment]
Hi Javier,

Thanks for pointing this out. I am currently cleaning up the repository and I will add the missing preprocessing step (we generated the labels as part of another project/repo). In the meantime, you can find the preprocessed labels on Google Drive: https://drive.google.com/file/d/1VT8stNV2E6nslfAWW--rCPvARMKN0n6m/view?usp=share_link

I hope that helps and sorry for the inconvenience!

Best,
Sebastian

**Comment by jsmithdlc** [comment]
I understand, thank you!
